### ISSUE TITLE
some questions with fomula (10) in the paper

### ISSUE THREAD

**Issue by Eyoahz1243fei** [autonomousvision/gaussian-opacity-fields#1]
Your work is really wonderful and gives me a lot of inspiration. But I have a little question. In your paper, you define the opacity of a 3D point x as the minimal opacity value among all training views or viewing directions by formula (10), but what you wrote under the symbol {min} was (r, t). I supposed that it should be written as (o, r). I'm not sure about it. It would be very kind of you if you can help me.

**Comment by niujinshuchong** [comment]
Hi, thanks for pointing this out. It is a typo and we will update it in the revision.
