### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by HuangWenH** [autonomousvision/gaussian-opacity-fields#10]
Hello, thank you for your work.
 I would like to train using my own dataset, but even with the 24GB VRAM of my RTX 3090 GPU, it is not enough. I am only using 200 images. How can I solve this problem?
![1c925b5b1a8468a00f9c9af90f1871f](https://github.com/autonomousvision/gaussian-opacity-fields/assets/145078967/d9681a65-fdfb-49f2-b7c4-cd244605e06b)

**Comment by StevenssW** [comment]
> 您好，怀念我的工作。 我想用自己的数据集进行训练，但即使使用 RTX 3090 GPU 的 24GB VRAM，也不够用。我只使用 200 张图像。我该如何要求？ ![1c925b5b1a8468a00f9c9af90f1871f](https://private-user-images.githubusercontent.com/145078967/326271332-d9681a65-fdfb-49f2-b7c4-cd244605e06b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzYyMDcsIm5iZiI6MTcxNjUzNTkwNywicGF0aCI6Ii8xNDUwNzg5NjcvMzI2MjcxMzMyLWQ5NjgxYTY1LWZkZmItNDlmMi1iN2M0LWNkMjQ0NjA1ZTA2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNzMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDA5ZDViZWIwODA5YjkwMDNkODg4MDAwYzNhNDE1YmVmNjZlODA2MDk0YWExMDU2NzMxODkzNWYwMDk4OGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uha95R6qUd6FtReWfkgD1FipqXoAj-ZcobYHtbs74MQ)

Have you solved it? I have the same problem as you.
