### ISSUE TITLE
Difference kernel size. Same output mesh.

### ISSUE THREAD

**Issue by DavidCao1993** [autonomousvision/gaussian-opacity-fields#12]
Appreciate to have the great work. I trainned the dataset and extracted mesh with difference kernel size. but the results have not changed.

**Comment by DavidCao1993** [comment]
the kernel size 7:
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/24777577/fd8a09d3-c209-4cb5-a80d-3d125dad5a25)
the kernel size 4:

**Comment by niujinshuchong** [comment]
Hi, the kernel size is not used and it should be set to 0.0.
