### ISSUE TITLE
What's the difference between extract_mesh.py and extract_mesh_tsdf.py？

### ISSUE THREAD

**Issue by sumai-1998** [autonomousvision/gaussian-opacity-fields#23]
Which result of these two .py is the 'Ours' in the teaser? 
When i run extract_mesh_tsdf.py, there is a error :

Rendering progress:   0%|                                     | 0/49 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "extract_mesh_tsdf.py", line 107, in <module>
    extract_mesh(model.extract(args), args.iteration, pipeline.extract(args))
  File "extract_mesh_tsdf.py", line 90, in extract_mesh
    tsdf_fusion(dataset.model_path, "test", iteration, cams, gaussians, pipeline, background, kernel_size)
  File "extract_mesh_tsdf.py", line 64, in tsdf_fusion
    frustum_block_coords = vbg.compute_unique_block_coordinates(
RuntimeError: [Open3D Error] (void open3d::t::geometry::kernel::voxel_grid::DepthTouchCUDA(std::shared_ptr<open3d::core::HashMap>&, const open3d::core::Tensor&, const open3d::core::Tensor&, const open3d::core::Tensor&, open3d::core::Tensor&, open3d::t::geometry::kernel::voxel_grid::index_t, float, float, float, float, open3d::t::geometry::kernel::voxel_grid::index_t)) /root/Open3D/cpp/open3d/t/geometry/kernel/VoxelBlockGridCUDA.cu:197: No block is touched in TSDF volume, abort integration. Please check specified parameters, especially depth_scale and voxel_size

Have you ever met this error？

**Comment by niujinshuchong** [comment]
Hi, we use extract_mesh.py for the ours in the teaser figure. extract_mesh_tsdf.py use tsdf fusion with rendered depth maps.
