### ISSUE TITLE
No texture or verter color

### ISSUE THREAD

**Issue by yang1hu** [autonomousvision/gaussian-opacity-fields#24]
Hi! thanks for your great project! I find that when i get the mesh, i cannot get verter color or texture. is there any things i can do to get the color

**Comment by Shhfdsdf** [comment]
i saw some other methods use texture to get the color ,like Gaussian Studio,and Sugar seems like use UV to get the color

**Comment by yang1hu** [comment]
> Hi, we have return the rendered color of each points during opacity evaluation. You can check it out here https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/gaussian_renderer/__init__.py#L215

when i generate the mesh,if i can make a simple modification to get the color on the verter

**Comment by niujinshuchong** [comment]
Hi, I just added mesh texturing. Please pull the latest code and extract the mesh with `--texture_mesh`.
