### ISSUE TITLE
How does filter_3D affect?

### ISSUE THREAD

**Issue by zhouilu** [autonomousvision/gaussian-opacity-fields#25]
Tthanks for your great project! I have some questions
* How does filter_3D affect? like scale or opacity
* There are many artifacts in the sky, but not in the original 3d-gs

**Comment by niujinshuchong** [comment]
Hi, can you also show a comparison with original 3DGS? How is your training images looks like?

**Comment by zhouilu** [comment]
here is original 3dgs, less floaters in sky.
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/20485626/9791aff6-b02d-46f4-bdbd-e31f4acc1643)

**Comment by niujinshuchong** [comment]
@zhouilu Thanks for reporting this. Can you share your data so I can try to figure out the reason?
