### ISSUE TITLE
When I run cmake ., I encounter the following issue. Moreover, the environment setup is the same as on GitHub. 

### ISSUE THREAD

**Issue by waynechyr** [autonomousvision/gaussian-opacity-fields#26]
CMake Error at /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:751 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v

  The output was:

  255

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/usr/local/cuda/bin:/usr/local/cuda/bin:/home/wayne/anaconda3/envs/gof/bin:/home/wayne/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs -L/usr/lib/x86_64-linux-gnu

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -D__CUDA_ARCH__=300 -E -x c++ -DCUDA_DOUBLE_MATH_FUNCTIONS
  -D__CUDACC__ -D__NVCC__ -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1
  -D__CUDACC_VER_BUILD__=243 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --gnu_version=90400 --allow_managed -arch compute_30 -m64
  -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name
  "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library
  "/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc"
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name
  "CMakeCUDACompilerId.cu" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  #$ ptxas -arch=sm_30 -m64 "tmp/CMakeCUDACompilerId.ptx" -o
  "tmp/CMakeCUDACompilerId.sm_30.cubin"

  ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

  # --error 0xff --

Call Stack (most recent call first):
  /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
(gof) wayne@wayne-chyr:~/data/gaussian-opacity-fields/submodules/tetra-triangulation$ cmake .
CMake Error at /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:751 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v

  The output was:

  255

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/usr/local/cuda/bin:/usr/local/cuda/bin:/home/wayne/anaconda3/envs/gof/bin:/home/wayne/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs -L/usr/lib/x86_64-linux-gnu

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -D__CUDA_ARCH__=300 -E -x c++ -DCUDA_DOUBLE_MATH_FUNCTIONS
  -D__CUDACC__ -D__NVCC__ -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1
  -D__CUDACC_VER_BUILD__=243 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --gnu_version=90400 --allow_managed -arch compute_30 -m64
  -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name
  "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library
  "/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc"
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name
  "CMakeCUDACompilerId.cu" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  #$ ptxas -arch=sm_30 -m64 "tmp/CMakeCUDACompilerId.ptx" -o
  "tmp/CMakeCUDACompilerId.sm_30.cubin"

  ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

  # --error 0xff --

Call Stack (most recent call first):
  /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /home/wayne/anaconda3/envs/gof/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!

**Comment by niujinshuchong** [comment]
Hi, maybe you need to specify your own cuda path such as
```
export CPATH=/usr/local/cuda-11.3/targets/x86_64-linux/include:$CPATH
```

**Comment by waynechyr** [comment]
First of all, thank you for your reply. Yes, my CUDA path is indeed /usr/local/cuda-11.3/targets/x86_64-linux/include. When I used the method you provided and then used the $CPATH command, I found that it showed "bash: /usr/local/cuda-11.3/targets/x86_64-linux/include: : No such file or directory". I think this is because there are two colons ":" appearing. So, after removing the colon, it became "bash: /usr/local/cuda-11.3/targets/x86_64-linux/include: is a directory". However, when I then ran "cmake .", I still encountered the same error. Did I make a mistake in any of the steps? Could you please help me with this? Thank you!

**Comment by waynechyr** [comment]
> Hi, maybe you need to specify your own cuda path such as
> 
> ```
> export CPATH=/usr/local/cuda-11.3/targets/x86_64-linux/include:$CPATH
> ```

First of all, thank you for your reply. Yes, my CUDA path is indeed /usr/local/cuda-11.3/targets/x86_64-linux/include. When I used the method you provided and then used the $CPATH command, I found that it showed "bash: /usr/local/cuda-11.3/targets/x86_64-linux/include: : No such file or directory". I think this is because there are two colons ":" appearing. So, after removing the colon, it became "bash: /usr/local/cuda-11.3/targets/x86_64-linux/include: is a directory". However, when I then ran "cmake .", I still encountered the same error. Did I make a mistake in any of the steps? Could you please help me with this? Thank you!

**Comment by rkakash59** [comment]
same issue, @waynechyr did you solve this?

**Comment by waynechyr** [comment]
> same issue, @waynechyr did you solve this?

Hi, I have already solved this problem. Maybe you can refer to this GitHub link.
https://github.com/NVlabs/instant-ngp/issues/747

**Comment by Aur1anna** [comment]
> > same issue, @waynechyr did you solve this?
> 
> Hi, I have already solved this problem. Maybe you can refer to this GitHub link. [NVlabs/instant-ngp#747](https://github.com/NVlabs/instant-ngp/issues/747)

Hi, thanks a lot for your sharing!
However, after i use “sudo apt remove nvidia-cuda-toolkit”, i run “apt-cache policy nvidia-cuda-toolkit”,and it shows as this:
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/161825526/f72878c9-233a-4196-aab8-92cfc439d389)

and i do can run “cmake .” but maybe something wrong?or it is just right for this step?this is it shows after i run cmake .:
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/161825526/b53d2adc-d435-4d4a-a6a0-1e37daa242ba)

 and after cmake and make , i still cant extract the mesh, the error shows :
 
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/161825526/a07e04bc-d31d-4ab4-b84f-1af8101651ce)

I wonder if i made a mistake in any step.I would appreciate it if you could please help me with this.
 Thank you!

**Comment by waynechyr** [comment]
@Aur1anna

**Comment by waynechyr** [comment]
> > > same issue, @waynechyr did you solve this?
> > 
> > 
> > Hi, I have already solved this problem. Maybe you can refer to this GitHub link. [NVlabs/instant-ngp#747](https://github.com/NVlabs/instant-ngp/issues/747)
> 
> Hi, thanks a lot for your sharing! However, after i use “sudo apt remove nvidia-cuda-toolkit”, i run “apt-cache policy nvidia-cuda-toolkit”,and it shows as this: ![image](https://private-user-images.githubusercontent.com/161825526/338202465-f72878c9-233a-4196-aab8-92cfc439d389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTUyMzYsIm5iZiI6MTcxODA5NDkzNiwicGF0aCI6Ii8xNjE4MjU1MjYvMzM4MjAyNDY1LWY3Mjg3OGM5LTIzM2EtNDE5Ni1hYWI4LTkyY2ZjNDM5ZDM4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwODM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2ExZGQwMTcyYTlmODBiYjU2NWQ1ZTBhZmNmMDBhMmQ3ZmZmOTc4NzgzMGY2OTAzZjI3ZGU1ZDRjY2RiZDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hlkR0Z3dRcqUG0D0gwWcrc1efLl7Ha5aHmIY5hazy98)
> 
> and i do can run “cmake .” but maybe something wrong?or it is just right for this step?this is it shows after i run cmake .: ![image](https://private-user-images.githubusercontent.com/161825526/338203819-b53d2adc-d435-4d4a-a6a0-1e37daa242ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTUyMzYsIm5iZiI6MTcxODA5NDkzNiwicGF0aCI6Ii8xNjE4MjU1MjYvMzM4MjAzODE5LWI1M2QyYWRjLWQ0MzUtNGQ0YS1hNmEwLTFlMzdkYWEyNDJiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwODM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjMxNGE3YWNkYmU4ZTU1NWE2NDYwMjBmZWVmNzg4YjU5MjA2MzM5NjAxMzNhMjkyNTMwZmU0NjhhZGJhNGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tzN_5geN_CV5cB1Z5s9UsLpESC5QVn9GmOSto4bnpdE)
> 
> and after cmake and make , i still cant extract the mesh, the error shows :
> 
> ![image](https://private-user-images.githubusercontent.com/161825526/338205228-a07e04bc-d31d-4ab4-b84f-1af8101651ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTUyMzYsIm5iZiI6MTcxODA5NDkzNiwicGF0aCI6Ii8xNjE4MjU1MjYvMzM4MjA1MjI4LWEwN2UwNGJjLWQzMWQtNGFiNC1iODRmLTFhZjgxMDE2NTFjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwODM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTM3ZDEyNGUyM2MyZjVlOWYyZWRhNTQyOWI0YjFhM2JhOWM5YTRjNWNkZDIyODBhNDdlMTRhMjYzM2VlYjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DgoWja2e17d0zlLUR8OHDqKFFj2X-6a7jTVA0smnRNI)
> 
> I wonder if i made a mistake in any step.I would appreciate it if you could please help me with this. Thank you!

"First of all, I think the previous execution seems correct. I wonder if it's because you forgot to run pip install -e ., which caused the related packages not to be installed."

**Comment by Aur1anna** [comment]
hi,thanks for reply! I didn't forget to run  pip install -e ., and tetra-nerf-0.1.1 installed successfully in pip list.

I also checked the tetranerf_cpp_extension.cpython-38-x86_64-linux-gnu.so in extension:
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/161825526/1192d636-0f61-4b33-b5fd-198be1f78c8e)
Is the format of this file correct？

I am very confused about reporting error in extract-mesh now,i have no idea how to fix this. Thank you again for your help！

**Comment by Aur1anna** [comment]
Hi, I try this again using pytorch1.12.1+cuda11.3 instead of 2.0.1+11.7, and by referring to your shared github link I can extract-mesh successfully now.

Thank you so much for your sharing and your generous help!

**Comment by waynechyr** [comment]
> Hi, I try this again using pytorch1.12.1+cuda11.3 instead of 2.0.1+11.7, and by referring to your shared github link I can extract-mesh successfully now.
> 
> Thank you so much for your sharing and your generous help!

I'm glad to have helped you. In fact, I initially tried changing environments as well. Some environments can indeed cause execution failures, but I'm not quite sure about the exact reasons.
