### ISSUE TITLE
Weird Surface Result on Tandt Dataset

### ISSUE THREAD

**Issue by Runyu-Zhou05** [autonomousvision/gaussian-opacity-fields#27]
Thank you for your great work! However, I have trouble with mesh extracting on the train scene of the [tandt](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/datasets/input/tandt_db.zip) dataset. My command:

```bash
MODEL_PATH="tandt/train"

python train.py -s ../../datasets/tandt/train -m outputs/$MODEL_PATH -r 2 --use_decoupled_appearance
python extract_mesh.py -m outputs/$MODEL_PATH --iteration 30000
python extract_mesh_tsdf.py -m outputs/$MODEL_PATH --iteration 30000
```

I got such weird meshes:

![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/149618011/57da345a-4f41-4a79-9302-bf3f422cd849)
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/149618011/81b7a7be-3d92-4d2c-9dcf-935d702316cb)
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/149618011/69c3a51e-198b-4787-99b0-a64689a1f1a9)

I can't see any pattern in it. Is there anything wrong?

**Comment by niujinshuchong** [comment]
Hi, TNT scenes are unbounded and our method can also extract meshes for the background regions. You need to zoom in to the center of the scene to check the center object. Here it looks like the ground plane. You should also enable double direction of faces.
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/13434986/f815b536-0c20-4b3f-8799-4b80305b20d7)

**Comment by Runyu-Zhou05** [comment]
> Hi, TNT scenes are unbounded and our method can also extract meshes for the background regions. You need to zoom in to the center of the scene to check the center object. Here it looks like the ground plane. You should also enable double direction of faces. ![image](https://private-user-images.githubusercontent.com/13434986/328575184-f815b536-0c20-4b3f-8799-4b80305b20d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDUzODgsIm5iZiI6MTcxNTE0NTA4OCwicGF0aCI6Ii8xMzQzNDk4Ni8zMjg1NzUxODQtZjgxNWI1MzYtMGMyMC00YjNmLTg3OTktNGI4MDMwNWIyMGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA1MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmI1ODU5YWRiNWE2NTFjZmQ4NzdhZGEzMWZkODJiOTdiMzVlYWYxNDg2NDRhY2Y5ZWNmMTdmZDA5NDUzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Ak57_SJ5i_d7ZSv5I9yz7ZC98yRAUKS2iHnHZrpAcw)

Hi, thank you for your quick response! Could you please recommend a viewer by which I can zoom in to see the details?

**Comment by niujinshuchong** [comment]
Hi, I use open3d for mesh viewer. I just uploaded the script of our mesh viewer. You can run it with 
```
python mesh_viewer.py your_mesh_path
```
