### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by TY424** [autonomousvision/gaussian-opacity-fields#28]
The function [depths_to_points()](https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/utils/depth_utils.py) is the same as 2DGS. This [improvement](https://github.com/hbb1/2d-gaussian-splatting/pull/8) may also be useful for gaussian-opacity-fields. 

```
grid_x, grid_y = torch.meshgrid(torch.arange(W)+0.5, torch.arange(H)+0.5, indexing='xy')
grid_x, grid_y = torch.meshgrid(torch.arange(W, device='cuda').float(), torch.arange(H, device='cuda').float(),indexing='xy')
```

**Comment by niujinshuchong** [comment]
Hi, thanks for pointing this out. I updated it.
