### ISSUE TITLE
some warnings during installing diff-gaussian-rasterization:invalid narrowing conversion from "double" to "float"

### ISSUE THREAD

**Issue by hot-dog** [autonomousvision/gaussian-opacity-fields#30]
there are some C++ compile warning as follow, will these warnings have negative impact on training?
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/5945046/92d75141-c442-41a3-b3ff-c39912c79f08)

**Comment by niujinshuchong** [comment]
Hi, I think it should be fine.
