### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by mudimingquedeyinmoujia** [autonomousvision/gaussian-opacity-fields#31]
Hi, I tried to modify the codes of Gaussians Representation while keeping your rasterizer parts (for the using of normal map and depth map). It works well at first, but I got:
RuntimeError: CUDA error: an illegal memory access was encountered
at the 114 line of your gaussian-opacity-fields/gaussian_renderer/__init__.py, that is :
"visibility_filter" : radii > 0

This problem occurs at the iteration of about 2k-5k, and it seems like a metaphysical problem. I can not fingure out why.
So I doubt are there any rubust problem in the CUDA codes?

**Comment by huahangc** [comment]
I also get this error which I use the GOF rasterization in my own dataset.

**Comment by niujinshuchong** [comment]
Could you check if you are already using this one https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620 ? Or can you be more specific for what you have changed and what kind of data you are using?

**Comment by mudimingquedeyinmoujia** [comment]
@niujinshuchong Hi, thanks for your reply. I solved the problem. This is because there are NAN input of gaussian rasterizer while the rasiterizer can not handle the situation. @huahangc I guess maybe there are NAN of your data or GS, so carefully check the NAN value before the rasterizer.

**Comment by huahangc** [comment]
@mudimingquedeyinmoujia Thanks. There does has nan value input of the gaussian rasterizer. But all loss turn to nan when I check the nan value of the input and turn the nan value to 0. How to solve this problem?

**Comment by 2693748650** [comment]
@mudimingquedeyinmoujia Hi！Could you please explain in detail how to solve this problem? I have also met the same problem, and I am struggling to know how to solve it.

**Comment by torracxiaokeai** [comment]
> @niujinshuchong Hi, thanks for your reply. I solved the problem. This is because there are NAN input of gaussian rasterizer while the rasiterizer can not handle the situation. @huahangc I guess maybe there are NAN of your data or GS, so carefully check the NAN value before the rasterizer.

hello! I wonder how you find NAN input of gaussian rasterizer? I have also met the same problem
