### ISSUE TITLE
When I run the `extract_mesh.py` I meet an error.

### ISSUE THREAD

**Issue by huahangc** [autonomousvision/gaussian-opacity-fields#32]
`ImportError: cannot import name 'tetranerf_cpp_extension' from partially initialized module 'tetranerf.utils.extension' (most likely due to a circular import) (/home/hh/anaconda3/envs/gof/lib/python3.8/site-packages/tetranerf/utils/extension/__init__.py)`
How to solve this problem? Has anyone meet this error?

**Comment by ywaison** [comment]
> `ImportError: cannot import name 'tetranerf_cpp_extension' from partially initialized module 'tetranerf.utils.extension' (most likely due to a circular import) (/home/hh/anaconda3/envs/gof/lib/python3.8/site-packages/tetranerf/utils/extension/__init__.py)` How to solve this problem? Has anyone meet this error?

23/5000

Hello, I also encountered the same problem, how did you solve it

**Comment by ghost** [comment]
Hi, I also meet the same problem, how did you solve it

**Comment by huahangc** [comment]
@Violetsli Sorry, I forgot how to solve it. You can try checking the import statements in the header of your Python file for any errors or unused imports.
