### ISSUE TITLE
How to extract the mesh from the trained gaussian point cloud without filter_3D attribute?

### ISSUE THREAD

**Issue by huahangc** [autonomousvision/gaussian-opacity-fields#34]
How to extract the mesh form the origin gaussian splatting point cloud by the `extract_mesh.py` ?

**Comment by niujinshuchong** [comment]
Hi, I think you need to change the code here https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/gaussian_renderer/__init__.py#L60 and https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/gaussian_renderer/__init__.py#L70 to use original 3DGS's point cloud. However, as pointed out in our mip-splatting paper, the dilation in 3DGS will introduce strong artifacts during rendering and thus also affects the opacity fields evaluation. 

I suggest you retraining your scene with GOF or mip-splatting.

**Comment by huahangc** [comment]
thank u.
