### ISSUE TITLE
Killed when run dtu_eval/eval.py

### ISSUE THREAD

**Issue by Shhfdsdf** [autonomousvision/gaussian-opacity-fields#36]
![20240515143044](https://github.com/autonomousvision/gaussian-opacity-fields/assets/140057828/c6f178b1-7ef9-4a1c-a318-3ac8fa9f4370)
hi, after i extracted the dtu mesh and used the code to eval it,it was shut down, i thought maybe it's because of some triangle noise,so i remove these artifacts manually ,and then eval it ,but it was still killed.

**Comment by niujinshuchong** [comment]
Hi, the eval script will sample many points on the surface. If the input mesh contains large faces for the background region (this is what you shown in the screenshot), it will generate a lot more points and might leads to memory issues. For this region, we use the TSDF fusion for the mesh evaluation for the DTU dataset.

**Comment by Shhfdsdf** [comment]
thanks!
