### ISSUE TITLE
Fail to build diff-gaussian-rasterization

### ISSUE THREAD

**Issue by Sunnyhong0326** [autonomousvision/gaussian-opacity-fields#4]
Hi, thanks for your nice work!
I am trying to run your code by following the steps provided but fail to build diff-gaussian-rasterization. Since I can't directly build with command pip install submodules/diff-gaussian-rasterization, I build it with command python setup.py install. However, it still doesn't work. This is the snapshot of error message:
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/66857678/bb524ab4-b8ea-4f47-ad2a-a955ee883554)
My system configuration is Ubuntu20.04 / RTX-2080ti.

**Comment by goometasoft** [comment]
Me too !

**Comment by Eyoahz1243fei** [comment]
me too ! ! !

**Comment by Eyoahz1243fei** [comment]
me too. I used 'sudo pip' and it still didn't work.

Processing ./submodules/diff-gaussian-rasterization
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-hdmnr97s/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-hdmnr97s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-hdmnr97s/pip-egg-info
         cwd: /tmp/pip-req-build-hdmnr97s/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-hdmnr97s/setup.py", line 13, in <module>
        from torch.utils.cpp_extension import CUDAExtension, BuildExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Eyoahz1243fei** [comment]
me too

**Comment by alvin528** [comment]
Same error. Did anyone solve it?

**Comment by Eyoahz1243fei** [comment]
> Same error. Did anyone solve it?
Because the file 'exponential.hpp' is missing in '/gaussian-opacity-fields/submodules/diff-gaussian-rasterization/third_party/glm/glm/'. you can see the solution here: 
https://github.com/autonomousvision/gaussian-opacity-fields/issues/6

**Comment by louisehuang07** [comment]
> > Same error. Did anyone solve it?
> > Because the file 'exponential.hpp' is missing in '/gaussian-opacity-fields/submodules/diff-gaussian-rasterization/third_party/glm/glm/'. you can see the solution here:
> > #6

Thank you so much! It worked

**Comment by Sunnyhong0326** [comment]
It works! Thank you!
