### ISSUE TITLE
OOM when run extract_mesh.py

### ISSUE THREAD

**Issue by poorGiser** [autonomousvision/gaussian-opacity-fields#42]
When I run extract_mesh.py for my custom data,I get OOM error in this code snippet. 
I use RTX 4090.
![code](https://github.com/autonomousvision/gaussian-opacity-fields/assets/129021453/bbfa1567-00c8-4797-a1fa-e36eaa321252)
I want to know if it's because there are too many Gaussian in the scene or because of the graphics card.
Thanks.

**Comment by poorGiser** [comment]
Thank you for your reply. I'm using a portion of the UAV dataset with about 470 images. The origin image resolution is 4591x3435, then I set -- -resolution 4 to downsample the image. when I extract the image, the vertices.shape, tets.shape, alpha.shape = torch.Size([1, 35472411, 3]) torch.Size([237834521, 4]) torch.Size([35472411]), I don't know if that's a lot.
I will try your suggestions and get back to you, thank you.

**Comment by niujinshuchong** [comment]
Hi, 35M points is reasonable but you might be 24GB is not enough to run the marching tetrahedral algorithm. Are you able to extract the mesh by tuning the hyperparameters to use less Gaussians?

**Comment by poorGiser** [comment]
I changed [https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/train.py#L259](url) to gaussians.densify_and_prune(opt.densify_grad_threshold, 0.1, scene.cameras_extent, size_threshold) to delete more gaussians, then I I successfully extracted the mesh .But I don't know if this will lead to a decrease in surface quality.

**Comment by niujinshuchong** [comment]
Hi, could you try to use a smaller chunk size here: https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/utils/tetmesh.py#L55

If this dosen't work, the other solution is to save the temporary results in cpu and only move the data to gpu when it is used by changing the code here: 
https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/utils/tetmesh.py#L52
but this might slow down the process significantly.

**Comment by mawenjie1111** [comment]
> Hi, could you try to use a smaller chunk size here: https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/utils/tetmesh.py#L55
> 
> If this dosen't work, the other solution is to save the temporary results in cpu and only move the data to gpu when it is used by changing the code here: https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/utils/tetmesh.py#L52 but this might slow down the process significantly.

thank you for reply , i have solved this bug
