### ISSUE TITLE
ERROR: Maximal contributors are met. This should be fixed! 1024

### ISSUE THREAD

**Issue by huahangc** [autonomousvision/gaussian-opacity-fields#46]
Thanks for your great work. After I train the GOF in the `endonerf` dataset with the device mask, I extract the mesh that meets this error. How do you think I could solve this error?

**Comment by niujinshuchong** [comment]
Hi, how is your extracted mesh looks like? This is a warning means that the opacity evaluation might be inaccurate if all of gaussians fall inside a pixel. But usually the opacity will reaches its maximal after integrating over a these gaussians so the results is still correct. If your mesh looks good, then you can ignore it.

**Comment by huahangc** [comment]
@niujinshuchong Thanks for your reply. I discovered that my camera's intrinsic error was due to this error.

**Comment by Net-Maker** [comment]
I meet this error in DTU scan27 on my RTX3090. And the final mesh is wrong. Any reason for this?
![image](https://github.com/user-attachments/assets/236a8191-c0e2-4ae0-853c-bcd0fc62149c)
