### ISSUE TITLE
Why pixf is added by 0.5

### ISSUE THREAD

**Issue by YanhaoZhang** [autonomousvision/gaussian-opacity-fields#48]
Thanks for releasing the code. I was wondering in renderCUDA, why 0.5 is added to pixf? Thank you. 
```
float2 pixf = { (float)pix.x + 0.5f, (float)pix.y + 0.5f}; // TODO plus 0.5
```

**Comment by niujinshuchong** [comment]
Hi, +0.5 so that we are using the pixel center to create the ray otherwise it is the top-left corner of the pixel.

**Comment by YanhaoZhang** [comment]
Thanks a lot for your prompt reply. I know understand it.
