### ISSUE TITLE
Issues with Gaussian Opacity Field (GOF) Applied to Limited Viewpoint Images Resulting in Suboptimal Gaussians and Meshes

### ISSUE THREAD

**Issue by JiajieLi7012** [autonomousvision/gaussian-opacity-fields#57]
Hello,

I've been working on applying the Gaussian Opacity Field (GOF) approach to a scenario involving images with limited viewpoints. However, I encountered some problems where the trained Gaussians had more floaters compared to those obtained using the original 3DGS method. Do you have any insights on this observation? Additionally, the meshes extracted using GOF were not good.

![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/77574492/7ebc5c82-f3c7-4b33-b06a-b8746d1abe58)

![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/77574492/063538d2-8b6c-4501-aea5-e5d2980062b1)

Contrastingly, using the original 3DGS-based SuGaR method, both the Gaussians and the meshes yielded significantly better results. This raises a concern about whether GOF is best suited for scenarios that involve 360-degree image views. Could the issues I'm facing be related to the limited viewpoints of my images?

I would greatly appreciate any guidance or suggestions on how to optimize GOF for scenarios with limited viewpoints.

Thank you!

**Comment by niujinshuchong** [comment]
Hi, what do you mean by limited view points? Could you also share a comparison with SuGaR?

**Comment by JiajieLi7012** [comment]
Thank you for your timely response. "Limited Viewpoint Images" means that our input images are extracted from a video, which implies that they only observe the scene from a limited number of angles, rather than including images from nearly 360 degrees of different perspectives as in a synthetic dataset. As for the Gaussians and mesh results of SuGaR, they are shown in the following images. Note the full video includes hand and red bucket movement but the results of GOF shown before were obtained only using images before the red bucket movement with the hand masked out while the results of SuGaR were trained directly on the full video without any masking. But directly training GOF on the full video also resulted in extremely similar results shown before.

![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/77574492/cdf94b0a-1cc5-4185-9fcf-079a298a1adf)

  
![Screenshot 2024-06-11 at 11 43 29 PM](https://github.com/autonomousvision/gaussian-opacity-fields/assets/77574492/0311b48f-ba67-4389-afd5-fdb41794fa0f)

**Comment by niujinshuchong** [comment]
Hi, the result of SuGaR is indeed better. Can you share some of the rendered images during training in the log_images files. That might be helpful to understand the differences.

**Comment by JiajieLi7012** [comment]
Sure. Below are the rendered images at iteration 100, 20000, 30000 respectively.
![100](https://github.com/autonomousvision/gaussian-opacity-fields/assets/77574492/a1dfccef-041d-41e6-a39e-0abce19f6e85)

![20000](https://github.com/autonomousvision/gaussian-opacity-fields/assets/77574492/c30b2b48-a83e-4a44-89e5-c080831dea9f)

![30000](https://github.com/autonomousvision/gaussian-opacity-fields/assets/77574492/e076249c-0e77-4c05-9584-b440d67ddf6d)

**Comment by JiajieLi7012** [comment]
Thanks for sharing your insights. Just to make sure we are on the same page, do you mean limited views in the input images by "input images have limited baselines"?

**Comment by niujinshuchong** [comment]
Is your input images have little motion?

**Comment by JiajieLi7012** [comment]
Yes.
