### ISSUE TITLE
python mesh_viewer.py: [Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing

### ISSUE THREAD

**Issue by Aur1anna** [autonomousvision/gaussian-opacity-fields#59]
Hi! When I use python mesh_viewer.py, and the error shows like this :
![_EEK2W$7EWCIXMZHXCWIVYN](https://github.com/autonomousvision/gaussian-opacity-fields/assets/161825526/6eec40c7-e9bd-4f09-9c7d-58711a58ddae)
Any help will be appreciated!

**Comment by niujinshuchong** [comment]
Hi, you need to have a physical monitor in order to use open3d's viewer. Otherwise you can download your mesh and open it in meshlab or blender.
