### ISSUE TITLE
some question with ‘pip install submodules/diff-gaussian-rasterization’

### ISSUE THREAD

**Issue by Eyoahz1243fei** [autonomousvision/gaussian-opacity-fields#6]
it seems like the file 'exponential.hpp' is missing.
And I use the same file in your repo 'mip': 
https://github.com/autonomousvision/mip-splatting/blob/main/submodules/diff-gaussian-rasterization/third_party/glm/glm/exponential.hpp

**Comment by msouiai** [comment]
Yup, 
is was missing for me too. Just get it from here
https://github.com/g-truc/glm/blob/5c46b9c07008ae65cb81ab79cd677ecc1934b903/glm/exponential.hpp

**Comment by niujinshuchong** [comment]
Hi, it should be resolved with https://github.com/autonomousvision/gaussian-opacity-fields/pull/17.
