### ISSUE TITLE
Can I extract mesh from trained vanilla 3DGS model?

### ISSUE THREAD

**Issue by Runyu-Zhou05** [autonomousvision/gaussian-opacity-fields#61]
Hi, thanks for your great work! I wonder if it's possible to extract mesh from a trained vanilla 3DGS model so that I don't have to train it again using GOF. When I run mesh extraction directly it says filter_3D is missing in the point_cloud.ply file. Please let me know if I just need to do some minor modifications to the code. Thank you!

**Comment by niujinshuchong** [comment]
Hi, Yes as long as the underlying representation is 3D Gaussians. You could set the filter_3D to zero for that. 

But the original 3DGS codebase suffers from some artifacts (see our mip-splatting project https://niujinshuchong.github.io/mip-splatting/) and we fixed it in mip-splatting. This project GOF is built on mip-splatting's solution and there is some inconsistencies to the original 3DGS's rendering, therefore the results might not be very good. I would suggest you train your model with mip-splatting and extract the mesh with GOF or retrain your model with GOF.
