### ISSUE TITLE
How to render normals and depths

### ISSUE THREAD

**Issue by xiaobiaodu** [autonomousvision/gaussian-opacity-fields#62]
Hi

Thanks for your excellent work! I am interested in how to render normals and depths. 
When I run 'python render.py', it does not output normal and depth maps. 
Could you please share how to do that?

**Comment by flww213** [comment]
So how should they be rendered? Can you give me some hints？

**Comment by flww213** [comment]
> So how should they be rendered? Can you give me some hints？
I understand. Like the 169 or so lines of code in train.py, it gets depth and normal directly from rendering

**Comment by niujinshuchong** [comment]
Hi, the depth and normal is rendered by defaults. You can refer to here https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/train.py#L193-L235 for how to visualize it.
