### ISSUE TITLE
Question about computing Sigma in forward.cu on line 265

### ISSUE THREAD

**Issue by Meng-Wei** [autonomousvision/gaussian-opacity-fields#66]
Hi, thanks for your excellent work.

Regarding the computation of Sigma in forward.cu on line 265, why does the code transpose R_transpose as
	glm::mat3 Sigma = glm::transpose(R_transpose) * S_inv_square_R; ?
Should it be
	glm::mat3 Sigma = R_transpose * S_inv_square_R; ?

Thank you in advance.

**Comment by niujinshuchong** [comment]
Hi, I think the naming is confusing. But the R_transpose here is the view to gaussian transform R. 

Sigma is `R^T @ S^-1 @ S^-1 @ R`. Therefore, it should be the first one.
