### ISSUE TITLE
about Eq(6)

### ISSUE THREAD

**Issue by zhouilu** [autonomousvision/gaussian-opacity-fields#69]
How is t* derived?

![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/20485626/0aeb4942-de05-473a-b22f-0aa9be45e322)

**Comment by niujinshuchong** [comment]
Hi, you can plug eq. 4 into eq. 5 and get a quadratic function of t which has closed form solution.

**Comment by zhouilu** [comment]
thanks~
