### ISSUE TITLE
Questions about Ray-Gaussian intersection

### ISSUE THREAD

**Issue by hwanhuh** [autonomousvision/gaussian-opacity-fields#72]
Hi, thank you for the great work! 

I have a question about the Ray-Gaussian intersection. 

When rendering a 3D GS scene using Ray-Gaussian intersection, it seems not to need a Jacobian matrix (of camera to ray space transform). 
If so, are there no perspective projection errors due to affine approximation? 

thank you!

**Comment by niujinshuchong** [comment]
Hi, Yes. There is no projection error in GOF.

**Comment by hwanhuh** [comment]
Oh, I think that is also a big strength of this work!

Then, will GOF support non-pinhole camera models such as fisheye? Do you have any plans to extend GOF to work with general camera models?

thanks!

**Comment by niujinshuchong** [comment]
Yes, it should work with other camera models. Unfortunately, I don't have a plan for that. But you just need to slightly change the CUDA code to accept camera rays as input.

**Comment by hwanhuh** [comment]
thank you for your reply!!

**Comment by cxzhou35** [comment]
Hi, I am sorry to bother you under this closed issue, but this is the only relevent topic I can found.

In the cuda implementation, you use the EWA splatting to do gaussian tile overleap testing? This need a Jacobian matrix, why you say that there is no perspective projection? Though the progress of computing alpha doesn't use the splatting method. I guess you mean this?
