### ISSUE TITLE
Mesh Extraction from ply files generated by other 3DGS methods

### ISSUE THREAD

**Issue by laliwang** [autonomousvision/gaussian-opacity-fields#73]
First thanks for your excellent work and sharing! I have noticed that you mentioned in your paper like this: `We also note that GOFs are a general formula as long as the scene representation is a set of 3D Gaussians. For example, we can use it to extract a mesh from a pretrained 3DGS [Kerbl et al. 2023] or Mip-Splatting [Yu et al. 2024a] model.`

However, when I use your provided extract_mesh.py script for ply files generated by the original 3DGS, some errors accur as follows:
```
Traceback (most recent call last):
  File "extract_mesh.py", line 164, in <module>
    extract_mesh(model.extract(args), args.iteration, pipeline.extract(args), args.filter_mesh, args.texture_mesh)
  File "extract_mesh.py", line 132, in extract_mesh
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/code1/wjh/Lang3DGS/gaussian-opacity-fields/scene/__init__.py", line 86, in __init__
    self.gaussians.load_ply(os.path.join(self.model_path,
  File "/code1/wjh/Lang3DGS/gaussian-opacity-fields/scene/gaussian_model.py", line 444, in load_ply
    filter_3D = np.asarray(plydata.elements[0]["filter_3D"])[..., np.newaxis]
  File "/code1/wjh/anaconda3/envs/gof/lib/python3.8/site-packages/plyfile.py", line 715, in __getitem__
    return self.data[key]
  File "/code1/wjh/anaconda3/envs/gof/lib/python3.8/site-packages/numpy/core/memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
ValueError: no field of name filter_3D
```
So I just wonder if it is possible to directly use your extraction script for ply files generated by other 3DGS methods as mentioned in your paper. Thanks for your early reply!

**Comment by niujinshuchong** [comment]
Hi, currently only mip-splatting's pretrained model is supported. 

For 3DGS model, you need to change the code to load the pretrained model and set the filter_3D to zero.

**Comment by laliwang** [comment]
Thanks for your early reply! And then do you mean that I only need to add a filter_3D attribute to the 3DGS model generated by other methods and manually assign a value of 0? Thanks!
