### ISSUE TITLE
how to handle this problem?

### ISSUE THREAD

**Issue by luoshuiyue** [autonomousvision/gaussian-opacity-fields#76]
![图片](https://github.com/user-attachments/assets/e10055cc-154d-41a4-b01c-91673b7e1218)

**Comment by niujinshuchong** [comment]
Hi, it seems like there is no valid_points which means that all the input points are outside of all camera frustums. This is very strange. Could you check if this is the case?

**Comment by luoshuiyue** [comment]
Yes, it is. I used the wrong .ply. Now it works.
