### ISSUE TITLE
about the size of mesh

### ISSUE THREAD

**Issue by qianfanshen** [autonomousvision/gaussian-opacity-fields#80]
Hello,

I encountered an issue while working with the mipnerf360 dataset, specifically the "garden" scene. After training, the generated mesh resulted in a PLY file that is 1.7 GB in size. When I try to open this file in MeshLab, the software crashes due to the file size.

Is there any way to reduce the file size or optimize the mesh so that it can be handled more easily by MeshLab or other visualization tools?

Thank you for your assistance!

**Comment by niujinshuchong** [comment]
Hi, I use open3d to visualise the mesh. You can try the code here: https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/mesh_viewer.py.

**Comment by qianfanshen** [comment]
thanks a lot, i was able to visualize the mesh using open3d, however, it was hard for me to move or rotate the mesh maybe due to the file size. Another problem was that there existed many fragment meshes in the space like this.
<img width="660" alt="截屏2024-08-29 01 21 48" src="https://github.com/user-attachments/assets/bfaa99ad-d113-4efe-a474-73daf09f3ffa">

 How can I reduce or eliminate the fragment meshes to obtain a cleaner reconstruction? the command i ran was just`python scripts/run_mipnerf360.py`

**Comment by niujinshuchong** [comment]
Hi, you can try to use `--filter_mesh` when you extract the mesh. Some of mesh in the sky might be filtered.

**Comment by qianfanshen** [comment]
Thank you very much!
