### ISSUE TITLE
Details of mesh extraction and paper reproduction

### ISSUE THREAD

**Issue by zhejia01** [autonomousvision/gaussian-opacity-fields#84]
We noticed that you mentioned in the paper "Therefore, we employ a filtering step for the tetrahedral cells, removing any cell whose edges connect non-overlapping Gaussians. Gaussians are considered non-overlapping when the length of the edge connecting them exceeds the sum of their maximum scales, i.e., maximum 3-sigma extent dimension." and annotate the code in "extract_mesh.py", line 52, " we should filter the cell if it is larger than the gaussians", but we haven't found related code. Would you please help us implement this part of your paper?

**Comment by niujinshuchong** [comment]
Hi, it's implemented here https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/extract_mesh.py#L113-L118. You can enable it by `--filter_mesh`.

**Comment by zhejia01** [comment]
I get it! Thanks for your help!
