### ISSUE TITLE
Mesh Extracted from Custom Dataset Example

### ISSUE THREAD

**Issue by jianxiapyh** [autonomousvision/gaussian-opacity-fields#88]
Hi,

I've been following the steps for the Custom Data Example and reached the extracted mesh stage. Due to memory constraints, I had to use a downsampling factor of 4 instead of 2, but I kept everything else as specified in the instructions. However, the extracted mesh doesn't seem to look as expected. Could you provide any insight into potential causes for this issue?

![image](https://github.com/user-attachments/assets/a41b67e0-ad05-4e85-9b58-ca7cb4795578)

Thanks again for your assistance!

**Comment by niujinshuchong** [comment]
Hi, the extracted mesh includes background and you need to zoom into the center of the scene in meshlab 
![image](https://github.com/user-attachments/assets/ca953601-5bde-4370-a7d0-afdebcbf3fd6)

**Comment by jianxiapyh** [comment]
Hi, @niujinshuchong . Thank you for the insight! I noticed in other issues that you mentioned needing a bounding box to separate the object from the background. Could you suggest the quickest way to identify such a region?

**Comment by niujinshuchong** [comment]
Hi, it depends on your scene, you can manually annotate a box with mesh lab and then use the bounding box to filter the Gaussian when extracting the mesh. You can add your code here: https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/scene/gaussian_model.py#L392-L397

**Comment by jianxiapyh** [comment]
Got it. Thanks!
