### ISSUE TITLE
For tetra-triangulation，make error

### ISSUE THREAD

**Issue by llianxu** [autonomousvision/gaussian-opacity-fields#9]
Thanks for your impressive work!  when I compile the tetra-triangulation, I meet this error in make phase:
```
error: template argument 1 is invalid
  132 | GAL::compute_average_spacing<Concurrency_tag>(L, nb_neighbors);
```

**Comment by ingra14m** [comment]
Hi @llianxu, I think this error stems from the `CGAL ` version. In the version below CGAL 5.1, there is no `Parallel_if_available_tag`. `CGAL >= 5.1` cannot be installed in Python3.7 and below.

So, you need to upgrade your python to python-3.8 and reinstall CGAL through `conda install conda-forge::cgal`.

**Comment by llianxu** [comment]
thank you！ I will try your method

**Comment by zebin-dm** [comment]
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/94420096/12600bc8-ebe5-4997-800f-bbdf2fbfef9a)
my CGAL==5.61. but i still cause the same error above.

**Comment by niujinshuchong** [comment]
Hi, this part is not used and it removed. Please pull the latest code and try again.

**Comment by niujinshuchong** [comment]
I supposed it is resolved.
