### ISSUE TITLE
Nerf Synthetic Mesh Reconstruction Extra Plane

### ISSUE THREAD

**Issue by tatsoko** [autonomousvision/gaussian-opacity-fields#94]
Hello, I have used run_nerf_synthetic.py script and my mesh result has a weird long plane in it. How can I fix this issue?
Thanks in advance!
![image](https://github.com/user-attachments/assets/2b9a9615-a9e9-44e0-9cbb-46709ee688bf)
![image](https://github.com/user-attachments/assets/276b0d07-5ba7-463e-b19e-47afaf984135)

**Comment by niujinshuchong** [comment]
Hi, you could try setting the far plane to 6 during mesh extraction. See here https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/extract_mesh.py#L153. You should also remove the saved cells.pt file as it will be different when the Gaussian points change.

**Comment by tatsoko** [comment]
Thank you very much, it's fixed.
