### ISSUE TITLE
Texture mesh color overflow

### ISSUE THREAD

**Issue by fanwei360** [autonomousvision/gaussian-opacity-fields#95]
Hello, thanks for your excellent work! I'm extracting texture mesh and some of the mesh vertex color is not correct, especially the white area. There will be a phenomenon similar to color overflow, is there any way to improve this problem?
Thanks in advance if someone solves it.
![图片1](https://github.com/user-attachments/assets/7ae41c3a-2aaf-41eb-946a-8049ad0e0b11)

**Comment by niujinshuchong** [comment]
Hi, could you try to clip the value to 0 to 1 before convert it to uint8? 
https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/extract_mesh.py#L108

**Comment by fanwei360** [comment]
Thank you for timely reply!
The color overflow problem was solved by cropping the color to (0,1).
